name: Run Interop Workflow
on:
  workflow_call:
    inputs:
      testground_endpoint:
        description: testground_endpoint
        required: false
        type: string
      testground_runner:
        description: testground_runner
        required: true
        default: 'local:docker'
        type: string
      collect_name:
        description: collect_name
        required: true
        type: string
jobs:
  run_test:
    runs-on: [self-hosted, linux, x64, testground]
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: setup testground
        uses: ./.github/actions/setup-testground
        with:
          testground_endpoint: ${{ inputs.testground_endpoint }}

      - name: build the plan
        shell: bash
        run: ./build.sh
        working-directory: ./libp2p/ping-interop
        env:
          INPUT_TESTPLAN_A: go-v0.19
          INPUT_VERSION_A: v0.19.1
          INPUT_VERSION_B: v0.11.0
          INPUT_TESTPLAN_B: go-v0.11
          TESTGROUND_ENDPOINT: ${{ inputs.testground_endpoint }}

      - name: run the test
        shell: bash
        id: run
        run: |
          testground healthcheck --runner ${{ inputs.testground_runner }} --fix
          testground plan import --from ./libp2p --name libp2p;
          testground run composition -f ./libp2p/ping-interop/_compositions/2-versions.toml | tee run.out
          ./check_result.sh;

      - name: Collect test ouputs
        shell: bash
        if: ${{ steps.run.outputs.testground_id && (success() || failure()) }}
        run: |
          testground collect \
            --runner=${{ inputs.testground_runner }} \
            --output ~/testground_output.tgz \
            "${{ steps.run.outputs.testground_id }}"

      - uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: ${{ inputs.collect_name }}
          path: |
            ~/testground_output.tgz
            ~/daemon.out

