name: "run remote"

on:
  push:
  schedule:
    - cron:  '*/30 * * * *'


jobs:
  run_libp2p_interop_on_remote_docker:
    uses: ./.github/workflows/run-interop.yml
    with:
      testground_endpoint: http://staging.ipdx.testground.ipfs.team
      testground_runner: local:docker
      collect_name: run_libp2p_interop_on_remote_docker
  run_libp2p_ping_on_remote_docker:
    needs: run_libp2p_interop_on_remote_docker
    if: always()
    uses: ./.github/workflows/run-ping.yml
    with:
      testground_endpoint: http://staging.ipdx.testground.ipfs.team
      testground_runner: local:docker
      collect_name: run_libp2p_ping_on_remote_docker
  run_examples_pingpong_on_remote_docker:
    needs: run_libp2p_ping_on_remote_docker
    if: always()
    uses: ./.github/workflows/run-ping-pong.yml
    with:
      testground_endpoint: http://staging.ipdx.testground.ipfs.team
      testground_runner: local:docker
      collect_name: run_examples_pingpong_on_remote_docker
  run_sdk_rust_on_remote_docker:
    needs: run_examples_pingpong_on_remote_docker
    if: always()
    uses: ./.github/workflows/run-rust.yml
    with:
      testground_endpoint: http://staging.ipdx.testground.ipfs.team
      testground_runner: local:docker
      collect_name: run_sdk_rust_on_remote_docker